### ISSUE TITLE
Update instructions for macOS arm64: include directory

### ISSUE THREAD

**Issue by mizlan** [UCSD-PL/proverbot9001#115]
I recommend the inclusion of the following note for macOS arm64 users:

Run the following before installation so graphviz can be found, since on newer macOS systems homebrew installs into `/opt/homebrew`, **not** /usr/local/`.

```bash
export CPATH=/opt/homebrew/include
export LIBRARY_PATH=/opt/homebrew/lib
```

**Comment by HazardousPeach** [comment]
Good idea, thanks!
