### ISSUE TITLE
Unable to locate package software-common-properties

### ISSUE THREAD

**Issue by Scottyang8math** [UCSD-PL/proverbot9001#15]
I use Ubuntu 18.04.3 LTS, I had a trouble when I run this code:
 sudo apt install software-common-properties
However, Google tells me there is a packet name software-properties-common. So is this a mistake or a version problem?  Thanks~

**Comment by HazardousPeach** [comment]
It looks like `software-properties-common`  is the correct package. I've updated the README. Thanks!
