### ISSUE TITLE
Failed: make setup on coq-menhirlib dependency

### ISSUE THREAD

**Issue by geneing** [UCSD-PL/proverbot9001#16]
make setup fails on setup-coq-menhir step. It tries to pull from https://gitlab.inria.fr/fpottier/coq-menhirlib.git, but this repo is not publicly accessible and it's not possible to create a user account now. Please, change to pull from github clone.

**Comment by HazardousPeach** [comment]
Thanks for pointing that out! I fixed develop so that we just install menhir stuff from opam.
