### ISSUE TITLE
Some problems about proverbot.

### ISSUE THREAD

**Issue by ApolloLiZhaoyu** [UCSD-PL/proverbot9001#18]
Hi, I have a little problem when I run `make setup`: 

When setting up coq-menhirlib in src/setup.sh, it needs an Inria account. Can you provide a public github repository of coq-menhirlib in order to set up easily? And it seems like we should use `apt-get install -y graphviz-dev` to install graphviz-dev before we install pygraphviz in `make setup`.

And in your experiments, you compare proverbot9001 with CoqGym. However, when I run the experiment of CoqGym, it seems like there are less than 501 testcases of CompCert for CoqGym to extract. Are there exactly 501 testing proofs for CoqGym to prove in your setting?

**Comment by HazardousPeach** [comment]
The menhirlib thing  should be fixed by ae3ce9efa570ba0a0f50bac1dacd292a35473599, I accidentally left some old code in the setup script.
The graphviz-dev dependency is listed in the README under "prerequisites", though it's called libgraphviz-dev on some systems. 
Finally, CoqGym's preprocessing fails to process some of the CompCert proofs, which Proverbot9001 is able to handle. These proofs are not listed in the CoqGym total since it cannot even attempt them; we count these among proofs that CoqGym "fails".

**Comment by ApolloLiZhaoyu** [comment]
Hi, there are still some problems when running the script you provided:

when I run `make report` after running `make setup`, the terminal tells me:

python3.7 src/scrape.py  -v -c -j 1 --prelude=./CompCert ./backend/Locations.v > /dev/null
Makefile:16: Makefile.config: No such file or directory
make[1]: *** No rule to make target 'Makefile.config'.  Stop.
Attempting to load cached linearized version from CompCert/backend/Locations.v.lin
FAILED: In file ./backend/Locations.v:
'_' not provided. This case is not handled:
['CoqExn', [['loc', [[[Symbol('fname'), Symbol('ToplevelInput')], [Symbol('line_nb'), 1], [Symbol('bol_pos'), 0], [Symbol('line_nb_last'), 1], [Symbol('bol_pos_last'), 0], [Symbol('bp'), 15], [Symbol('ep'), 21]]]], ['stm_ids', [[3, 4]]], ['backtrace', [Symbol('Backtrace'), []]], ['exn', [Symbol('CErrors.UserError'), [Symbol('locate_library'), 'Unable to locate library Coqlib.']]], ['pp', [Symbol('Pp_glue'), [[Symbol('Pp_glue'), []], [Symbol('Pp_glue'), [[Symbol('Pp_glue'), [[Symbol('Pp_string'), Symbol('Unable')], [Symbol('Pp_print_break'), 1, 0], [Symbol('Pp_string'), Symbol('to')], [Symbol('Pp_print_break'), 1, 0], [Symbol('Pp_string'), Symbol('locate')], [Symbol('Pp_print_break'), 1, 0], [Symbol('Pp_string'), Symbol('library')], [Symbol('Pp_print_break'), 1, 0]]], [Symbol('Pp_string'), Symbol('Coqlib')], [Symbol('Pp_string'), Symbol('.')]]], [Symbol('Pp_string'), '']]]], ['str', 'Unable to locate library Coqlib.']]]
Failed file 1 of 1
python3.7 src/scrape.py  -v -c -j 1 --prelude=./CompCert ./backend/RTL.v > /dev/null
Makefile:16: Makefile.config: No such file or directory
make[1]: *** No rule to make target 'Makefile.config'.  Stop.
Attempting to load cached linearized version from CompCert/backend/RTL.v.lin
FAILED: In file ./backend/RTL.v:
'_' not provided. This case is not handled:
['CoqExn', [['loc', [[[Symbol('fname'), Symbol('ToplevelInput')], [Symbol('line_nb'), 1], [Symbol('bol_pos'), 0], [Symbol('line_nb_last'), 1], [Symbol('bol_pos_last'), 0], [Symbol('bp'), 15], [Symbol('ep'), 21]]]], ['stm_ids', [[2, 3]]], ['backtrace', [Symbol('Backtrace'), []]], ['exn', [Symbol('CErrors.UserError'), [Symbol('locate_library'), 'Unable to locate library Coqlib.']]], ['pp', [Symbol('Pp_glue'), [[Symbol('Pp_glue'), []], [Symbol('Pp_glue'), [[Symbol('Pp_glue'), [[Symbol('Pp_string'), Symbol('Unable')], [Symbol('Pp_print_break'), 1, 0], [Symbol('Pp_string'), Symbol('to')], [Symbol('Pp_print_break'), 1, 0], [Symbol('Pp_string'), Symbol('locate')], [Symbol('Pp_print_break'), 1, 0], [Symbol('Pp_string'), Symbol('library')], [Symbol('Pp_print_break'), 1, 0]]], [Symbol('Pp_string'), Symbol('Coqlib')], [Symbol('Pp_string'), Symbol('.')]]], [Symbol('Pp_string'), '']]]], ['str', 'Unable to locate library Coqlib.']]]
Failed file 1 of 1
......

It seems like there are still some problems in this project. Can you help me to fix it? Thanks.
