### ISSUE TITLE
Errors when following installation instructions

### ISSUE THREAD

**Issue by jibnew** [UCSD-PL/proverbot9001#22]
I'm on Ubuntu 20.10 LTE under Windows 10 WSL.
When running 
`sudo apt install software-properties-properties`
I get
```
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package software-properties-properties
```
Further,
`sudo add-apt-repository ppa:avsm/ppa
`
gives (amongst several OK lines)
```
Err:7 http://ppa.launchpad.net/avsm/ppa/ubuntu groovy Release
  404  Not Found [IP: 91.189.95.85 80]
```
and then
```
E: The repository 'http://ppa.launchpad.net/avsm/ppa/ubuntu groovy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```
After that, `opam` still seems to install OK. For `rustup` I get
```
No apt package "rustup", but there is a snap with that name.
Try "snap install rustup"

E: Unable to locate package rustup
```
It then installs through `snap` with some warnings. 
I had `graphviz` and `libgraphviz-dev`.
Finally I get stuck with `python3.7`: APT says
```
Package python3.7 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python3.7' has no installation candidate
```

Still tried to clone, get this:
```
Cloning into 'proverbot9001'...
The authenticity of host 'github.com (140.82.121.3)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no/[fingerprint])?
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

```

Please advise

**Comment by HazardousPeach** [comment]
Okay, a few different things here:

For OPAM, it's important that you get version 2.0, otherwise you won't be able to get recent versions of Coq. Last I checked, the version of OPAM available in the Ubuntu repositories was older than that. First, check what version of opam you have with:

**Comment by jinxing1990** [comment]
Hi, I believe for the first error, it is supposed to be

`sudo apt install software-properties-common`

instead of

`sudo apt install software-properties-properties`

**Comment by jibnew** [comment]
> 
> 
> Okay, those instructions were for an older version of Ubuntu, so theres a few different things here:
> 
> For OPAM, it's important that you get version 2.0, otherwise you won't be able to get recent versions of Coq. But since it looks like you're on ubuntu 20.10 (based on the "groovy" string when you tried to use the ppa), the version in the repositories should work fine.

Seems like I now have it:
```
502:~/> sudo apt search opam
Sorting... Done
Full Text Search... Done
libopam-file-format-ocaml-dev/groovy 2.0.0-2 amd64
  Parser and printer for the opam file syntax

libopamgt-dev/groovy 10.8.0.0.201+dfsg.1-1 amd64
  Development files for libopamgt0

libopamgt0/groovy 10.8.0.0.201+dfsg.1-1 amd64
  Omni-Path fabric management API library

opam/groovy,now 2.0.5-1ubuntu1 amd64 [installed]
  package manager for OCaml

opam-doc/groovy,now 2.0.5-1ubuntu1 all [installed,automatic]
  package manager for OCaml (documentation)

opam-installer/groovy,now 2.0.5-1ubuntu1 amd64 [installed,automatic]
  Utility handling (un)installation of Opam .install files
```
> It looks like `rustup` from snap is working for you, but if you have any issues, the recommended way to install rustup is through this site: https://rustup.rs/ .

How do I check whether it works or not?
 
> For python, any version _later_ than 3.7 will also work. It looks like the default `python3` package on Ubuntu 20.10 is python 3.8, so just installing the `python3` package should do the trick.

I have it:
```
507:~/> python3 --version
Python 3.8.6
```
> As for your inability to clone, it looks like your machine isn't recognizing the host key of github. The prompt should pause right after "Are you sure you want to continue connection (yes/no/[fingerprint])?", and if you type "yes", it should allow you to clone.

With "yes" it says
```
508:~/git/> git clone git@github.com:UCSD-PL/proverbot9001.git
Cloning into 'proverbot9001'...
Warning: Permanently added the RSA host key for IP address '140.82.121.4' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
> Please let me know if you have any other issues!
> 
> Alex

Thank you, Alex!

**Comment by jibnew** [comment]
> 
> 
> Hi, I believe for the first error, it is supposed to be
> 
> `sudo apt install software-properties-common`
> 
> instead of
> 
> `sudo apt install software-properties-properties`

Then I seem to be fine with it:
```
510:~/> sudo apt install software-properties-common
Reading package lists... Done
Building dependency tree
Reading state information... Done
software-properties-common is already the newest version (0.99.3.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by HazardousPeach** [comment]
Oh, for the repository cloning, it looks like you don't have an account key set up with Github. You can either set that up in your settings for private key login, or you can use the https clone link, https://github.com/UCSD-PL/proverbot9001.git
