### ISSUE TITLE
Can Proverbot9001 use PyCoq?

### ISSUE THREAD

**Issue by brando90** [UCSD-PL/proverbot9001#26]
@HazardousPeach Can Proverbot9001 be modified to use PyCoq (either of the too)?

PyCoq by Emilio: https://github.com/ejgallego/pycoq
PyCoq by IBM: https://github.com/IBM/pycoq

would there need to be big modifications?

useful general discussions, related links/discussions:
- https://github.com/princeton-vl/CoqGym/discussions/70
- https://github.com/princeton-vl/CoqGym/discussions/71
- https://github.com/HazardousPeach/coq_serapy/issues/2
- https://github.com/UCSD-PL/proverbot9001/issues/26
- https://github.com/princeton-vl/CoqGym/discussions/74
- https://coq.discourse.group/t/machine-learning-and-hammers-for-coq/303/37

**Comment by HazardousPeach** [comment]
Coq_Serapy is a higher level interface than PyCoq, so the best course of action would probably be to use PyCoq as a new backend to Coq_Serapy, and leave the Coq_Serapy interface intact. But, the README on the PyCoq repo says that it doesn't "handle errors correctly", so it's not clear that it's ready for Proverbot9001-scale. It also only supports Coq 8.13 and 8.14, which are too new for some of the benchmarks we'd like to run on. And the repo hasn't been touched in almost six months, so it's not clear that it's under active development and these issues might be resolved.
