### ISSUE TITLE
Scripts for generating Proverbot's CoqGym data set and evaluation interactions

### ISSUE THREAD

**Issue by brando90** [UCSD-PL/proverbot9001#27]
try to migrate conversation here because CoqDiscuss is creating issues with the number of links. Original conv here: https://coq.discourse.group/t/machine-learning-and-hammers-for-coq/303/42

ps2: related links/discussions:
- https://github.com/princeton-vl/CoqGym/discussions/70
- https://github.com/princeton-vl/CoqGym/discussions/71
- https://github.com/HazardousPeach/coq_serapy/issues/2
- https://github.com/UCSD-PL/proverbot9001/issues/26
- https://github.com/princeton-vl/CoqGym/discussions/74
- https://coq.discourse.group/t/machine-learning-and-hammers-for-coq/303/37
- https://github.com/UCSD-PL/proverbot9001/issues/27

**Comment by HazardousPeach** [comment]
When my team originally ran Proverbot on the CoqGym benchmarks, we did so with much manual effort. Since then, we've decided to make the benchmarks more first-class, and automate more of the process of setting them up. The scripts in question are `install_coqgym_deps.sh`, `build_coqgym_projects.sh` and `scrape_coqgym_projects.sh`. Since running this much coq code can be quite computational expensive, these scripts are designed to run on a cluster using the [Slurm](https://slurm.schedmd.com/) cluster management software. With some small modifications they should also run on a single machine though, simply replace calls to `sbatch` and the `sbatch-retry` script with running the target directly.

This repo uses the other repo you're talking about, coq_serapy, as a submodule, and they are often developed together. coq_serapy provides all the functionality for dealing with coq files and states, but not broader opam state. The rest is handled in scripts in this repo which use coq_serapy.

Coq_serapy, and thus this project, require Coq 8.10-8.12.2. This is because the corresponding coq_serapi versions (note the "i", here I mean emilios project) to those versions of coq have a relatively stable text interface, so the same python code can interact with all of them. As these API's mature and get more stable, we'll hopefully be able to support more versions.

**Comment by brando90** [comment]
Also, curious, what are the equivalent files for comp_cert? That seems a little simpler so it could be a nice one to use too for prototyping? Or at least the split file is simpler.

**Comment by brando90** [comment]
(fyi this is in the `develop` branch)

**Comment by brando90** [comment]
@HazardousPeach sorry for the spam Alex. But one more question. I am very interested in running your Proverbot9001 in general. If I download the weights I assume they are bound to some Coq version so I want to make sure if I train my own things I use the right Coq version. I know you gave a range of version 8.10-8.12.2. Is there an exact version that I do to avoid incompatibility issues or training on different version or avoiding that the performance difference are due to training on different Coq version?

This would be super valuable to me! Thank you Alex!

**Comment by brando90** [comment]
> @HazardousPeach sorry for the spam Alex. But one more question. I am very interested in running your Proverbot9001 in general. If I download the weights I assume they are bound to some Coq version so I want to make sure if I train my own things I use the right Coq version. I know you gave a range of version 8.10-8.12.2. Is there an exact version that I do to avoid incompatibility issues or training on different version or avoiding that the performance difference are due to training on different Coq version?
> 
> This would be super valuable to me! Thank you Alex!

I will infer for now (please correct me Alex if I am mistaken!) that the Coq version used to train Proverbot9001 is coq 8.10 based on the name of the switches in comp cert & some of coq gym's json specificiation:
```
    {
        "project_name": "constructive-geometry",
        "train_files": [
            "problems.v",
            "affinity.v",
            "basis.v",
            "orthogonality.v",
            "part1.v",
            "part3.v",
            "part2.v"
        ],
        "test_files": [],
        "switch": "coq-8.10"
    },
```

and

```

        "project_name": ".",
        "switch": "coq-8.10",
        "train_files": [
            "./cfrontend/Cshmgen.v",
            "./cfrontend/Initializersproof.v",
            "./cfrontend/Csharpminor.v",
            "./cfrontend/Cstrategy.v",
            "./cfrontend/SimplLocalsproof.v",
...
```

Now I only need to figure out how to install a specific coq version using opam. Hopefully this SO will eventually have a usable answer for ppl: https://stackoverflow.com/questions/54394510/how-does-one-switch-to-a-specific-version-of-coq-especially-when-managing-coq

**Comment by HazardousPeach** [comment]
1. Yes, I mistyped, the scripts are called `build_coq_projects.sh` and `scrape_coq_projects.sh`.
2. The only arguments the scripts should need is `-j<n>` if you want to use multiple threads, but as I said the scripts will need to be modified to be used in a single-machine or non-slurm-cluster context. The order is `install_deps`, then `build`, then `scrape`. 
3. The CompCert equivalents are
     a. Installing dependencies is done in `src/setup.sh`, but that's a mix of Proverbot9001 and CompCert stuff. The part that's equivalent to `install_coqgym_deps.sh` is: 
```
    opam pin add coq 8.11.0
    opam pin -y add menhir 20190626
```
     b. To build CompCert, it should be sufficient to make sure your opam env is setup, `cd` into the `CompCert` directory, and run `make`
     c. To scrape CompCert, you can just run `make data/compcert-scrape.txt` (or add -j for more threads)
4. If you use any of those Coq versions, the pre-trained weights should work fine. In the context of running CompCert by itself, I was using Coq 8.11.0 (as you can see in the above answer).

**Comment by brando90** [comment]
> 4. If you use any of those Coq versions, the pre-trained weights should work fine. In the context of running CompCert by itself, I was using Coq 8.11.0 (as you can see in the above answer).

I think you mean coq 8.10? Just based on the name of the switch? (both comp cert and coq gym use the same switch).

Thanks for the response! I think it will be very useful! :)

**Comment by HazardousPeach** [comment]
Either should work. The splits file format is new, so the one for CompCert was created when I was setting up CoqGym stuff, and I set it to a switch that I already had working. But prior to this infrastructure, I used 8.11.0 for CompCert.

**Comment by HazardousPeach** [comment]
Also, to answer your question about using particular versions of Coq in Opam, you just have to run `opam pin add coq <version>` to install that version of coq and make sure all other packages in the switch are compatible with it.

**Comment by brando90** [comment]
> https://stackoverflow.com/questions/54394510/how-does-one-switch-to-a-specific-version-of-coq-especially-when-managing-coq

what is the difference of doing that and doing `opam install coq <version>`?

Btw thanks for the help!

**Comment by brando90** [comment]
> Either should work. The splits file format is new, so the one for CompCert was created when I was setting up CoqGym stuff, and I set it to a switch that I already had working. But prior to this infrastructure, I used 8.11.0 for CompCert.

Ok so the fact the name of the switch says:
```
"switch": "coq-8.10",
```
is a bug but it should actual coq version you used was `8.11`? Apologis if I am very pendantic on this point. I am just scared/worried of spending lots of time and compute to trian a model, generate data for the wrong coq version compared to your Proverbot9001! I want to avoid that issue at all costs if possible. 

Appreciate your help! :)

**Comment by HazardousPeach** [comment]
Err, no basically I've used both 8.10.2 and 8.11.0 for CompCert. *Prior* to setting up CoqGym, I was using 8.11.0 for CompCert. But when I started setting up CoqGym, and created the splits file format, I made the splits file for CompCert use the same 8.10.2 switch I was using for CoqGym. But I haven't actually tested CompCert under this configuration yet. So, if you want to be abundantly cautious, you should change the switch in that file to 8.11. But I was planning on using 8.10.2 for it going forward, and fixing issues as they arrive (I don't really anticipate any).

**Comment by HazardousPeach** [comment]
To answer your opam question, `opam install coq <version>` will install coq to a particular version *right now*, but next time you try to install a package that depends on it, say coq-mathcomp-ssreflect, it'll try to install the newest version of that package, and it will update coq to a newer version to allow that. But if you run `opam pin add coq <version>` instead, it'll understand that you want to *keep* coq on that version in the future, and it'll pick versions of other packages accordingly.

**Comment by brando90** [comment]
> But I was planning on using 8.10.2 for it going forward, and fixing issues as they arrive (I don't really anticipate any).

Curious, why were you planning to downgrade to 8.10.2 going forward (for both data sets I assmue)? It sounds like you trained Proverbot9001 with 8.10.2 for CoqGym and for CompCert 8.11. So do the weights correspond to CoqGym or CompCert?

Thanks again for the clarifications.

**Comment by brando90** [comment]
Btw, I'm also curious, Coq gym has so many coq projects. I'm surprised it's possible to install a single opam switch with a single ocaml compiler and single coq version and have them ALL work. How is that possible? It seems like a (beautiful) miracle (?) to me.

**Comment by brando90** [comment]
also, how do I make sure I install the right version of serapi? got some serapi anomaly error from coq_serapy https://coq.zulipchat.com/#narrow/stream/256331-SerAPI/topic/debugging.20interactions.20with.20serapi/near/285751587

**Comment by HazardousPeach** [comment]
1. I was planning to downgrade to Coq 8.10.2 going forward because the Coq version doesn't usually matter that much in terms of proving the kinds of proofs Proverbot9001 usually finds, and so I prioritize using fewer versions of Coq that are compatible with more projects. The pre-trained weights correspond to CompCert, but weights work across Coq versions.
2. CoqGym was originallly designed such that all projects would run under a single Coq version, coq 8.9. However, since we don't support 8.9 in Proverbot9001, we actually use two different Coq versions and switches for running CoqGym under Proverbot, 8.10.2 and 8.12.2 . The `coqgym_projs_splits.json` file specifies which version should be used for which projects, and the scripts for installing dependencies, building, and scraping, as well as the search code, switches to the proper version for each project.
3. To install the right version of coq-serapi, it should be sufficient to pin Coq to one of the supported versions, and then install coq-serapi. If you just install the Coq version without pinning, installing coq-serapi after will override that and upgrade coq to the latest supported version.

**Comment by brando90** [comment]
@HazardousPeach Hi Alex. Thanks so much for your patience and help. It's appreciated.

I am curious about another thing. How did you deal with the fact that the coq projects have different dependencies when installing each coq project in Coq Gym? Did you create a different opam switch for each project? Or did you solve it in a different way?

**Comment by brando90** [comment]
> 1. build_coq_projects.sh

https://github.com/UCSD-PL/proverbot9001/blob/develop/build_coq_projects.sh

**Comment by brando90** [comment]
@HazardousPeach hi alex! I see that you are looping through the coq projs according to the splits json file. But I must admit that:
```
    echo "#!/usr/bin/env bash" > coq-projects/$project/make.sh
    echo ${INIT_CMD} >> coq-projects/$project/make.sh
    if $(jq -e ".[] | select(.project_name == \"$project\") | has(\"build_command\")" \
         coqgym_projs_splits.json); then
        BUILD=$(jq -r ".[] | select(.project_name == \"$project\") | .build_command" \
                   coqgym_projs_splits.json)
    else
        BUILD="make"
    fi

    if $(jq -e ".[] | select(.project_name == \"$project\") | has(\"build_partition\")" \
            coqgym_projs_splits.json); then
        PART=$(jq -r ".[] | select(.project_name == \"$project\") | .build_partition" \
                   coqgym_projs_splits.json)
        SBATCH_FLAGS+=" -p $PART"
    fi

    if $(jq -e ".[] | select(.project_name == \"$project\") | has(\"timeout\")" \
         coqgym_projs_splits.json); then
        TIMEOUT=$(jq -r ".[] | select(.project_name == \"$project\") | .timeout" \
                     coqgym_projs_splits.json)
        SBATCH_FLAGS+=" --time=${TIMEOUT}"
    fi

    SWITCH=$(jq -r ".[] | select(.project_name == \"$project\") | .switch" coqgym_projs_splits.json)

    echo "eval \"$(opam env --set-switch --switch=$SWITCH)\"" >> coq-projects/$project/make.sh

    echo "$BUILD $@" >> coq-projects/$project/make.sh
    chmod u+x coq-projects/$project/make.sh
    (cd coq-projects/$project && sbatch --cpus-per-task=${NTHREADS} $SBATCH_FLAGS -o build-output.out make.sh)
```
is rather mysterious to me. The only ways I know how to build a coq project is when

1. by running `opam pin` when there is an `*.opam` file e.g. as in `['opam', 'pin', '-y']
               + root_option()
               + ['--switch', switch]
               + [coq_package, coq_package_pin]` https://github.com/brando90/pycoq/blob/bcf4c2014409e182403806821241c995ddddcb13/pycoq/opam.py#L213

2. or by running `coq_makefile -f _CoqProject -o CoqMakefile` then `make` e.g. https://github.com/brando90/pycoq/tree/main/debug_proj

**Comment by brando90** [comment]
> With some small modifications they should also run on a single machine though, simply replace calls to `sbatch` and the `sbatch-retry` script with running the target directly.

@HazardousPeach I don't have slurm installed in my cluster or any HPC. What removing all sbatch calls and running the files directly with `sh` be sufficient you think? (or source)
