### ISSUE TITLE
why does `install_coqgym_deps.sh` need to sync opam state to local?

### ISSUE THREAD

**Issue by brando90** [UCSD-PL/proverbot9001#52]
why do we need this?
```
# Sync opam state to local
rsync -av --delete $HOME/.opam.dir/ /tmp/${USER}_dot_opam | tqdm --desc="Reading shared opam state" > /dev/null
```
in the `install_coqgym_deps.sh`?

I actually don't understand what it's doing either really.

**Comment by brando90** [comment]
similar question:
```
# Finally, sync the opam state back to global
rsync -av --delete /tmp/${USER}_dot_opam/ $HOME/.opam.dir | tqdm --desc="Writing shared opam state" > /dev/null
```

What is this?

**Comment by brando90** [comment]
Also, note I don't have sudo power in my hpc so I am happy to do things to my local opam root and local opam bins etc.

**Comment by brando90** [comment]
those dirs don't exist for me, hope it doesn't create issue for me:
```
$ ls /tmp/${USER}_dot_opam/
ls: cannot access '/tmp/brando9_dot_opam/': No such file or directory
$ ls $HOME/.opam.dir
ls: cannot access '/dfs/scratch0/brando9/.opam.dir': No such file or director
```

**Comment by HazardousPeach** [comment]
Ah, current development of Proverbot is being done on a particular cluster at UMass Amherst which has weird permissions on the shared file systems. You can remove those lines for your setup.
