### ISSUE TITLE
why do you create two switches in your install_coqgym_deps.sh?

### ISSUE THREAD

**Issue by brando90** [UCSD-PL/proverbot9001#53]
One here for coq 8.10:
```
# Create the 8.10 switch (cmd options opam switch create SWITCH [COMPILER])
opam switch
opam switch create coq-8.10 4.07.1
eval $(opam env --switch=coq-8.10 --set-switch)
opam pin add -y coq 8.10.2

# Install dependency packages for 8.10
opam repo add coq-extra-dev https://coq.inria.fr/opam/extra-dev
...
```
then one here for coq 8.12:
```
# Create the coq 8.12 switch
opam switch create coq-8.12 4.07.1
eval $(opam env --switch=coq-8.12 --set-switch)
opam pin add -y coq 8.12.2

# Install the packages that can be installed directly through opam
opam repo add coq-released https://coq.inria.fr/opam/released
```

I find this confusing. Why don't all the coq-gym projects use the same coq version and therefore a single opam switch?

**Comment by HazardousPeach** [comment]
There is unfortunately no version of Coq for which all the projects build. Some haven't been updated in a while, so they don't work on more modern versions of Coq, while others have been updated without providing a backwards-compatible version, so they don't work on older versions of Coq. I'm not the developer of these projects, so I can't speak to why they have or haven't been updated; in one case I filed an issue for a backwards compatible version, or at least providing the older version on OPAM, but it doesn't always make sense for the authors to make sure their stuff works on multiple versions.

**Comment by brando90** [comment]
> There is unfortunately no version of Coq for which all the projects build. Some haven't been updated in a while, so they don't work on more modern versions of Coq, while others have been updated without providing a backwards-compatible version, so they don't work on older versions of Coq. I'm not the developer of these projects, so I can't speak to why they have or haven't been updated; in one case I filed an issue for a backwards compatible version, or at least providing the older version on OPAM, but it doesn't always make sense for the authors to make sure their stuff works on multiple versions.

cool. But then how do you make sure you can actually extract the data from them? Do you have a different opam switch with a different coq version installed for each? Or how is this problem solved?

Thanks for the response!

**Comment by brando90** [comment]
I'm also puzzled, your model is trained with data coming from a combination of version of coq? @HazardousPeach 

Thanks for your time, really appreciated :)
