### ISSUE TITLE
Can the contents of read-opam.sh script be shared?

### ISSUE THREAD

**Issue by brando90** [UCSD-PL/proverbot9001#54]
I noticed the build_coq_project.sh has this:
```
INIT_CMD="~/opam-scripts/read-opam.sh"
```
which seems to be written a bunch of places when making the make.sh file for each coq project e.g.
```
for project in $(jq -r '.[].project_name' coqgym_projs_splits.json); do
    SBATCH_FLAGS=""

    echo "#!/usr/bin/env bash" > coq-projects/$project/make.sh
    echo ${INIT_CMD} >> coq-projects/$project/make.sh
...
```
can the contents of that file be shared? (since path doesn't start at proverbot)

Thanks for the help Alex! :)

**Comment by HazardousPeach** [comment]
Ah yeah that's the same rsync stuff you noticed earlier, which gets around
permission issues on a particular development cluster. If you're running on
a single machine or sane cluster, you should be able to set INIT_CMD to the
empty string
