### ISSUE TITLE
when to use remake? e.g. coquelicot uses remake instead of make clean -C path2coq_proj

### ISSUE THREAD

**Issue by brando90** [UCSD-PL/proverbot9001#66]
I saw one project uses remake instead of make:
```
        "project_name": "coquelicot",
        "train_files": [],
        "test_files": [
            "theories/Coquelicot.v",
            "theories/Series.v",
            "theories/KHInt.v",
            "theories/PSeries.v",
            "theories/ElemFct.v",
            "theories/SF_seq.v",
            "theories/Seq_fct.v",
            "theories/Hierarchy.v",
            "theories/Lub.v",
            "theories/RInt_analysis.v",
            "theories/Iter.v",
            "theories/Rbar.v",
            "theories/Lim_seq.v",
            "theories/Continuity.v",
            "theories/AutoDerive.v",
            "theories/Equiv.v",
            "theories/Derive_2d.v",
            "theories/Markov.v",
            "theories/RInt_gen.v",
            "theories/RInt.v",
            "theories/Complex.v",
            "theories/Compactness.v",
            "theories/Derive.v",
            "theories/Rcomplements.v"
        ],
        "switch": "coq-8.10",
        "build_command": "./configure.sh && ./remake"
```

why is it? can we just use make?

**Comment by HazardousPeach** [comment]
Makefiles and ReMakefiles are just different build systems that a project author could choose to use. Each offers relatively similar functionality, but maybe slightly different features and different syntax. But each one requires that you have a recipe file describing the build process in their own language, so the builder doesn't get a choice; whatever the project author decided to use, that's what the project builder has to use. So to be concrete, you can only use `make` if there is a `Makefile` present in the directory, and you can only use `./remake` if there is a `remake` file present in the directory.
