### ISSUE TITLE
when `configure x86_64-linux `needed?

### ISSUE THREAD

**Issue by brando90** [UCSD-PL/proverbot9001#67]
related: https://github.com/UCSD-PL/proverbot9001/issues/65

**Comment by HazardousPeach** [comment]
This seems like a duplicate issue... I already answered why you need to configure Compcert in another thread, it's really just project dependent. Each project can have an arbitrary set of instructions to build it, we're lucky that they're mostly one or two commands that I was able to add to the json by hand.
