### ISSUE TITLE
why are you doing gitsubmodule update then git submodule init -- isn't the reverse the standard?

### ISSUE THREAD

**Issue by brando90** [UCSD-PL/proverbot9001#71]
ref: https://stackoverflow.com/questions/3796927/how-do-i-git-clone-a-repo-including-its-submodules/3796947#3796947

Quoting:
> You have to do two things before a submodule will be filled:
```
git submodule init 
git submodule update
```

**Comment by HazardousPeach** [comment]
Fixed by 9b3bfed85eefecd68749650b1be5fef4c155c828 and ec3102d857bb3c00d1511b7142ecc18a53e7d273
