### ISSUE TITLE
Is the .gitignore file correct? Shouldn't it not have a forward slash?

### ISSUE THREAD

**Issue by brando90** [UCSD-PL/proverbot9001#75]
It is trying to git add some changes:
<img width="969" alt="Screenshot 2023-02-04 at 7 00 03 PM" src="https://user-images.githubusercontent.com/1855278/216799226-82e27d70-e744-45d4-aed4-4db667c7ba0c.png">
but they are on the gitignore file:
```
/.gcroots/
*__pycache__/
/CompCert/
/coq-projects/
/coq/
/coq-serapi/
/darknet/
*.aux
*.glob
*.swp
*.vo
/coq-menhirlib/
/data/scrape.txt
/data/scrape.bkp
report-*
report/
*-weights*
*.mypy_cache/*
*/.mypy_cache/*
*.lock
```

shouldn't it be:
```
/.gcroots/
*__pycache__/
CompCert/
coq-projects/
/coq/
/coq-serapi/
/darknet/
*.aux
*.glob
*.swp
*.vo
/coq-menhirlib/
/data/scrape.txt
/data/scrape.bkp
report-*
report/
*-weights*
*.mypy_cache/*
*/.mypy_cache/*
*.lock
````

**Comment by HazardousPeach** [comment]
Uhh not sure, you didn't specify which files you're trying to add, and I don't really understand the semantics of the starting slash very well.
