### ISSUE TITLE
sharing the already build opam environment?

### ISSUE THREAD

**Issue by brando90** [UCSD-PL/proverbot9001#84]
I was thinking that perhaps it's possible to checkpoint the entire dependencies and share them?

For example, wouldn't it be easier to share it with `opam lock`? At least for the short term?

> opam-lock - Create locked opam files to share build environments across hosts.

related: https://discuss.ocaml.org/t/how-does-one-pin-freeze-a-version-of-the-dependencies-of-an-opam-project-package-and-then-install-the-project-with-such-specified-dependencies/11424/3
related: https://stackoverflow.com/questions/75452407/how-does-one-pin-freeze-a-version-of-the-dependencies-of-an-opam-project-package

**Comment by HazardousPeach** [comment]
If you pin to commits this might work, but it's not going to solve the problem of opam releases disappearing. If you can come up with script modifications to do this and tests to make sure it works, I'd love to merge that. For now, closing this issue.
